apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-tunnel-credentials
  namespace: iot-dashboard
spec:
  encryptedData:
    cert.pem: AgAPctLYbUobtKDKCtz09KltH1HBdp0xP8HEd8W7I3eLcjIM+8JeXKU6JSIA8GlTYQUnVs/77dbskw+kN3iE0xBVw3kqWoNqk0WWmFLFeamokHB9RLlBrPoVO5Oo+uPZALjeowGEb6zVddbo3MEJPYGhkWvjQGGtSojTJqdDlHoeMr4V3g9p+2OZ2rvFWEiDWYRunPIFSqf3zOdcltio8qFLdzPjiiGI8cu9Eor6hbx4OfwBFxJ40bdwkiluoNE2ZIZ7AmVMh4usNJ15yDmKLsf0EMDHyt98Vby6wYo498rzZEE2EX6Uk9GMaO2vVGA8Swh0Ijg3epC85OKperrN2KsbP3yv9FUp/CvIlSR8ScfeU/cQosAbQlm3p8avMYvnFvcvKKvHYwQJTb2lHS4gUeUOXLN0ElRn7wkT+K6hMkU5aIuyA8eM1isljXQwI80A0tF5Ru03VLupZfricTPMr8+8liWkmU5mFZPFHx08t3TyX2TtAYeSun7J59NBSxJsmOBFXpoyYeW7e4AX5YJJEWAae2VYvHrwrj5xhhtTS3ew3PZBpYVuoPX2yIZ75eHjh17pxEZXgCr4r40mTl9nfO5NEQbpynl7TkoHIHC22Ln8eRkp15wB01KZTJu30G9S+3NFiEp2KgTTEeLwLt+hX11k1zq1wsBJMxa+rqyQ+VlUrm8mtaybQmId43vn83kPDKf/MM0G9+RDnOjaHhuiybhfwMYqse5FZEez15BF790A7U2DBJiJf8XCA5PG0SKowafcSs1FGfwE9487j25KEoS/XUBi543/eo6McK3jhqbyosMhj15drrd8IroRIvIq8KkwKpWcSUEGt8jC2Ynbc9x1gF7+rgTa37XLlwqJdlKZQXgaBGYiFG8oy8X0hYHLPP5kOc6/DjzOy2YGE319glJmalr8l2dta3dJUOPSVeYKoPLasa6iLXpCskPpdJmExFcwDgkXrvehkrdu3Ak+MAixJ6CWb+CwlloK6M47Nsv3Bk19+9frgOnbl5n8HR60OtADDHf1ddy/I2nhxVoFcAFjAmnH8BoCmg5N+w==
    credentials.json: AgCSzR+aUMW317yUcJHreLZVw6gubMumeWPw5HFD1uovI46T7Q+cD4Ho566RGrSM9eSzxvVHD6d2EmlIfoB6twrYaByyLvybsIGBINYe1XTcJPP7mi9qls5QfUsvS8W2svgnlwsyKZzEzZVDpm6EC0vRMMy0hiJQwdSUefZ44nZLED+BGwIWtlm7eZP3A25u4rE7n2/RbWmhDInRzQ5VtREwkRqfzZ7jdU/7muLsp4+3xgp9S9Uceghb3ko0QiBHU3kPz9jKOl0AZWZHMeIKz4HscaoCwtmdpSSKk5BwDO7rTkgq/ppMxkmgH/9akrzNgURdB164kOrX+PZyH0WfRT9GMBgapI3cilN9oa5aH+Ol8IiKBxaQdDMo81eIKJCbUrr1Fjq1aH3yAgbgH2ZczeiRfcWVL2v0ey1yyf/eVYV7946Am4pzlX1pxyIWe8L/gcm7OoQuexh0v7/D0pNwc0K2TQGHu1TFIcZedoLSoihw4MHFcJDCdXFy/wVThSP4ZKWbw3ycsWaPjgxzJd1xrzM92UZVZy7E2goMycUUccWHg6C3dN9e+JSGemL3bEnAZ5sKfFJDYHzVComVm5Suwc9ZV7D7V/dNy4P0/X1enoFAbvuD+fiEMkPGMbR0Hus+dyJrtQMOfVGXyqP+2UaFcJbqcuiSoKttJvHFFtTV+v7jkXCD6SP3I7ScaXfGrbQmThPR0O7855AQLcvK025+wVol/XVLAaasVTLjwps4pj3TOosjt2h6o1b7RrjSltmQnHdWxpazBao6Y93r9TSBOnI/P8HdHxcFEoq6Y4JlpDVxw2ikxsh9KsPNPA12TOzvOgiGdrtnCTsJIo08yWgF2+u/5IwtOrHK5JjrkpG9FKaYvOuyPsRBC8ynl7pXQ+kWYl3tXSmesUs+0j3MqYEl4os=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-tunnel-credentials
      namespace: iot-dashboard
---
