apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-tunnel-credentials
  namespace: iot-dashboard
spec:
  encryptedData:
    credentials.json: AgBrV6t2AEqryVETInEYXZgIuT6O3Ipygqr1Ke4Ou9k8deZbvgRQn+2EbFDiCaMq9eRsscnz4ovHeoIl6rRudloBrj2GfJh8LR2IT2e+HMAvKGFReG3ShaITkjr8SKL2iColMZEpFEtkhmlevUDuI0L9sUL+ML4pJfOCvDOmLeLSKupnexVmjFRWlBLYEeZaS2PW0uRUgiAUvvOMHvsdKkEpLXlhxAqrfNNSSxmAhTEG7oZ6JwhtgOM4Qxgnkt/jQOgJ2JmFZfAPOMeuRd4xgY0eUujuO3YE/UGVlf9iEpkMhFIKGIZCuIcOZ2Xgnhv62AT/TpCi/N3ScOomtprLu3VFSAnavo+wVFRRj9gGnWKqQHlTQsoX8Snu5h8EpRUBPChcr23EunCjR2mElNfRL5V+WbHfOPONeOPhkux6rqd739HeKHJWMKwIK10u6yrsIDEqq3VHAbIxrOB1cgwZufTV6WYiL5iPaUsLMB0UOse70p20WGR8cZETaPJZkiIG8MKYdhYQxUQG/bnkriXqeWRlXviQESnwEbtGwTgmgNSx+fIZ8F0sWShrvS1sxQoIKQew/C0iH+pRslKh4XlxgHs4agPQrEzTYbOAVSmtj1Sg+gylDvq9QNWS5MskcMVHA7VDXZ7VRt1m5WR3qE4WtE/W40F8qRTol+wObPKt34AYLfeqdaLEATXVmzlEq9rgiNpU8DVbx3Nnme6XNlvoq1g+/clZN56I8VzC0aKaP2Me8P5bYQezbwQTPgqtwL5RvJngWr4sDeAqTCVPhxLYXAuzYxaDY+ATbY8dgnVvo5yIocBvzEimVcBNI1X23hLRRc+KVH+k3AhKG3PDQgVaLn2mKX+UHyYCioRHs5omguB4GUpsG7aSxS4rhCJBgykmin0WOGlGaiKUi6sBInHbupc=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-tunnel-credentials
      namespace: iot-dashboard
---
