apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: iot-dashboard
type: Opaque
stringData:
  credentials.json: |
    {
      "AccountTag": "4c84b5d670564238dfccc3a7d4419965",
      "TunnelSecret": "rKPxHHDkcHJPsznQDRUgoOS5c7BvKzJqI0aDYPQ6o44=",
      "TunnelID": "0b0b67bc-20fa-400b-a3f9-b4bc8bbadd0e",
      "Endpoint": ""
    }
